version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpresstest
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - wordpresstest

  wordpress:
    ports:
      - "8000:80"
    depends_on:
      - db
    image: wordpress:latest
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wordpresstest
networks:
  wordpresstest:
volumes:
  db_data:
